// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCalorieTracker.Api.Data;

#nullable disable

namespace SmartCalorieTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325100927_AddDailyLogTargets")]
    partial class AddDailyLogTargets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartCalorieTracker.Api.Models.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodDictionaryId")
                        .HasColumnType("int");

                    b.Property<double>("GramsConsumed")
                        .HasColumnType("float");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TargetCalories")
                        .HasColumnType("float");

                    b.Property<double>("TargetCarbs")
                        .HasColumnType("float");

                    b.Property<double>("TargetFats")
                        .HasColumnType("float");

                    b.Property<double>("TargetProteins")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FoodDictionaryId");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("SmartCalorieTracker.Api.Models.FoodDictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("float");

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("float");

                    b.Property<double>("FatsPer100g")
                        .HasColumnType("float");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProteinsPer100g")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FoodDictionaries");
                });

            modelBuilder.Entity("SmartCalorieTracker.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("int");

                    b.Property<double>("DailyCarbsGoal")
                        .HasColumnType("float");

                    b.Property<double>("DailyFatsGoal")
                        .HasColumnType("float");

                    b.Property<int>("DailyProteinGoal")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartCalorieTracker.Api.Models.DailyLog", b =>
                {
                    b.HasOne("SmartCalorieTracker.Api.Models.FoodDictionary", "FoodDictionary")
                        .WithMany()
                        .HasForeignKey("FoodDictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodDictionary");
                });
#pragma warning restore 612, 618
        }
    }
}
